### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by xiaowuc2** [dylanmeca/ChatGPT-Python#1]
How did you get the link which is in the link section of your repository? is it free to make? like how did you hosted the code for free?

**Comment by dylanmeca** [comment]
Hi. 

## Hugging Face
![image](https://user-images.githubusercontent.com/55631040/225666259-b75c3e52-638d-47ff-8c23-6a2bac6688c6.png)
if you refer to the Hugging Face link, it's free to host the code there, but the price depends on whether the hosted consumes more cpu or uses gpu.

![image](https://user-images.githubusercontent.com/55631040/225664458-48c0ac1f-f213-4be2-9de5-60e4686f16cb.png)

To host the code on Hugging Face you can upload the code from the same website or create it from there, or use git.

![image](https://user-images.githubusercontent.com/55631040/225665700-df68ec21-d7eb-4e25-896d-6b52bdb4da7a.png)

And to find the link, you can click where it says: **Use via API**, and the link should appear there:

![image](https://user-images.githubusercontent.com/55631040/225670708-b5f0fa6c-8ebc-483a-9b93-001865230494.png)

## Google Colab
If you refer to the Google Colab link, where the code appears, it is free and even with the nvidia gpu. And for the code to appear there, all you have to do is upload a notebook created with jupyter to github. And in the same Google Colab, place the link of the github repository and there will be all the notebooks that are in the repository.

![image](https://user-images.githubusercontent.com/55631040/225668133-366bb07e-977e-4dc6-bc0a-5bb65a602f2a.png)

From there, simply click on the notebook and then copy the link that appears in your browser's search bar. Greetings 👍

**Comment by xiaowuc2** [comment]
thank you very much!
